/**
 * The theme that ships in the app. Every file here is original: the sounds,
 * cards, boot art and icons are generated by `tools/gen-default-theme.sh`, the
 * face is Inter, and the names are plain.
 */

import fixtureUrl from "../avatar/fixture.glb?url";
import { hex } from "../bootTheme";
import orbUrl from "./default/art/orb.png";
import settingsUrl from "./default/art/settings.png?inline";
import bootFlare from "./default/boot/flare.png?inline";
import bootMark from "./default/boot/mark.png?inline";
import bootOrb from "./default/boot/orb.png?inline";
import card1 from "./default/cards/1.jpg";
import card2 from "./default/cards/2.jpg";
import card3 from "./default/cards/3.jpg";
import card4 from "./default/cards/4.jpg";
import card5 from "./default/cards/5.jpg";
import card6 from "./default/cards/6.jpg";
import card7 from "./default/cards/7.jpg";
import card8 from "./default/cards/8.jpg";
import back from "./default/sounds/back.ogg";
import blade1 from "./default/sounds/blade-1.ogg";
import blade2 from "./default/sounds/blade-2.ogg";
import blade3 from "./default/sounds/blade-3.ogg";
import boot from "./default/sounds/boot.ogg";
import channelDown from "./default/sounds/channel-down.ogg";
import channelUp from "./default/sounds/channel-up.ogg";
import focus from "./default/sounds/focus.ogg";
import hudClose from "./default/sounds/hud-close.ogg";
import hudFocus from "./default/sounds/hud-focus.ogg";
import hudOpen from "./default/sounds/hud-open.ogg";
import hudSelect from "./default/sounds/hud-select.ogg";
import option from "./default/sounds/option.ogg";
import panelLeft from "./default/sounds/panel-left.ogg";
import panelRight from "./default/sounds/panel-right.ogg";
import select from "./default/sounds/select.ogg";
import toast from "./default/sounds/toast.ogg";
import transition from "./default/sounds/transition.ogg";
import type { Theme } from "./types";

export const DEFAULT_THEME: Theme = {
  id: "default",
  name: "Default",
  sounds: {
    option,
    panelLeft,
    panelRight,
    channelUp,
    channelDown,
    select,
    back,
    focus,
    transition,
    hudOpen,
    hudClose,
    hudFocus,
    hudSelect,
    blade1,
    blade2,
    blade3,
    boot,
    toast,
  },
  cards: [card1, card2, card3, card4, card5, card6, card7, card8],
  art: { orb: orbUrl, settings: settingsUrl },
  avatar: fixtureUrl,
  strings: {
    channels: ["Spotlight", "Friends", "Media Store", "Game Store", "My Console"],
    gameStore: "Game Store",
    mediaStore: "Media Store",
    dashboard: "Dashboard",
    gamertag: "Player Name",
    gamerscore: "Score",
  },
  boot: {
    animation: "drops",
    field: {
      greyTop: hex(0xa4a4a4),
      greyEdge: hex(0x3a3a3a),
      night: hex(0x0b2a1e),
      pale: hex(0xe2e6e1),
      settledEdge: hex(0x7f9a8c),
      settledMid: hex(0x93b3a2),
      settledGlow: hex(0xcdeede),
    },
    sphere: {
      base: hex(0x9aa198),
      shadow: hex(0x1c201c),
      specular: hex(0xf4fff0),
      rim: hex(0xb8e8d0),
      grain: 0.05,
    },
    mark: {
      angle: 0,
      width: 0.03,
      wall: hex(0x1f9a7a),
      floor: hex(0x6cf0c0),
      core: hex(0xe6fff2),
    },
    accent: hex(0x6cf0c0),
    orb: { url: bootOrb, width: 480, height: 480, cx: 240, cy: 240, rx: 200, ry: 200 },
    wordmark: { url: bootMark, width: 1192, height: 252 },
    flare: { url: bootFlare, width: 768, height: 360 },
    lockup: { orbX: 977.5, orbY: 441.5, orbRy: 144, markX: 536, markY: 595, markWidth: 882 },
  },
  fonts: [],
  cssVars: {},
};
