#!/usr/bin/env node
/**
 * Writes app/src/tvKeys.generated.ts from the TV's own settings description.
 *
 *   node tools/gen-tv-keys.mjs                       fetch /etc/palm/description.json over ssh
 *   node tools/gen-tv-keys.mjs path/to/description.json
 *   TV_HOST=root@192.168.1.40 node tools/gen-tv-keys.mjs
 *
 * Only the key names and their kind are baked in. Options, ranges and values are
 * read live from the settings service, because which options are valid depends
 * on the input, the picture mode and the HDR mode at the time. The pages offer
 * picture, sound, screen size and caption keys, minus anything that resets,
 * tests, calibrates or switches something off.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../app/src/tvKeys.generated.ts");
const host = process.env.TV_HOST ?? "root@192.168.1.37";

const raw = process.argv[2]
  ? readFileSync(process.argv[2], "utf8")
  : execFileSync(
      "ssh",
      ["-o", "BatchMode=yes", "-o", "LogLevel=ERROR", host, "cat /etc/palm/description.json"],
      {
        encoding: "utf8",
        maxBuffer: 1 << 26,
      },
    );
const description = JSON.parse(raw);

const DANGER =
  /reset|test|wizard|screenoff|oledpanel|pixelcleaning|isf|factory|calib|setup|detection|notification|key$|temp$|active$|perapp$|modified$|limitation|^devicecnt|^prev|supportatmos|enginestatus|^dtm|mastering|professional|applytoall|modesync$|^lgsoundsync|^coSound|^sound$|^soundOutputs$|^avMode$|^videoSource$|^displayType$|^sourceRatio$|adjustingLuminance/i;

const PAGES = [
  {
    id: "tv-picture",
    title: "TV Picture",
    description: "The TV's picture settings.",
    categories: ["picture", "aiPicture"],
    skip: /^(colorManagement|whiteBalance|colorGamut)|zoom|position|size$|ratio$/i,
  },
  {
    id: "tv-color",
    title: "Color Management",
    description: "Hue, saturation and luminance for each colour.",
    categories: ["picture"],
    only: /^colorManagement/i,
  },
  {
    id: "tv-white",
    title: "White Balance",
    description: "Gain and offset for each channel.",
    categories: ["picture"],
    only: /^whiteBalance/i,
  },
  {
    id: "tv-screen",
    title: "Screen Size",
    description: "Aspect ratio, zoom and position.",
    categories: ["aspectRatio", "picture"],
    only: /zoom|position|size$|ratio$|justscan|arc/i,
    skip: /^(aspectRatioPerApp|aspectRatioSettingActivePerApp)$/,
  },
  {
    id: "tv-sound",
    title: "TV Sound",
    description: "Where the TV sends its sound, and how it sounds.",
    categories: ["sound"],
  },
  {
    id: "tv-captions",
    title: "Captions",
    description: "How captions look.",
    categories: ["caption"],
  },
];

function kindOf(entry) {
  if (entry.vtype === "Range") return "r";
  if (entry.vtype !== "ArrayExt") return null;
  const values = (entry.values?.arrayExt ?? []).map((item) =>
    String(typeof item === "object" ? item.value : item),
  );
  if (values.length === 0) return null;
  const set = new Set(values);
  return set.size === 2 && set.has("on") && set.has("off") ? "b" : "e";
}

const seen = new Map();
for (const entry of description) {
  const ui = entry.ui ?? {};
  if (!ui.visible || !ui.active) continue;
  const kind = kindOf(entry);
  if (kind === null) continue;
  const id = `${entry.category}.${entry.key}`;
  if (!seen.has(id)) seen.set(id, { category: entry.category, key: entry.key, kind });
}

const pages = PAGES.map((page) => {
  const keys = [...seen.values()]
    .filter((item) => page.categories.includes(item.category))
    .filter((item) => !DANGER.test(item.key))
    .filter((item) => (page.only ? page.only.test(item.key) : true))
    .filter((item) => (page.skip ? !page.skip.test(item.key) : true))
    .sort((a, b) => a.key.localeCompare(b.key, "en", { sensitivity: "base" }));
  return { ...page, keys };
});

// A key belongs to the first page that claims it.
const claimed = new Set();
for (const page of pages) {
  page.keys = page.keys.filter((item) => {
    const id = `${item.category}.${item.key}`;
    if (claimed.has(id)) return false;
    claimed.add(id);
    return true;
  });
}

const body = pages
  .filter((page) => page.keys.length > 0)
  .map(
    (page) => `  {
    id: ${JSON.stringify(page.id)},
    title: ${JSON.stringify(page.title)},
    description: ${JSON.stringify(page.description)},
    keys: [
${page.keys.map((item) => `      [${JSON.stringify(item.category)}, ${JSON.stringify(item.key)}, ${JSON.stringify(item.kind)}],`).join("\n")}
    ],
  },`,
  )
  .join("\n");

writeFileSync(
  out,
  `// Generated by tools/gen-tv-keys.mjs from the TV's settings description. Do not edit.

export type GenKind = "b" | "e" | "r";

export interface GenPage {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly keys: readonly (readonly [category: string, key: string, kind: GenKind])[];
}

export const TV_GEN_PAGES: readonly GenPage[] = [
${body}
];
`,
);
for (const page of pages) console.log(page.id.padEnd(12), page.keys.length);
